// src/ui/react/components/BatchEditor.jsx
import React, { useState } from 'react';
import {
  getDisplayValue,
  parseExifDate,
  dtToExif,
} from '../../../core/index.js';

const sectionStyle = { padding: '12px', borderBottom: '1px solid var(--border-color, #ddd)' };
const groupStyle = { border: '1px solid #eee', borderRadius: '6px', padding: '10px', marginBottom: '10px' };
const labelStyle = { fontSize: '13px', color: '#555', display: 'block', marginBottom: '4px' };
const inputStyle = { padding: '6px 8px', minHeight: '32px', borderRadius: '4px', border: '1px solid #ccc', flex: 1, minWidth: 0 };
const btnStyle = { padding: '6px 10px', minHeight: '32px', borderRadius: '4px', cursor: 'pointer' };
const smallBtn = { ...btnStyle, padding: '4px 8px', fontSize: '12px' };

// Batch editing: field groups with apply/clear/reset; time shift section.
// Empty input = no change. Apply writes the value to all images.
export function BatchEditor({ images, store, presets, applyPresetToImage, getPresetDisplayName, t }) {
  const list = images || [];
  const [dateVal, setDateVal] = useState('');
  const [timeVal, setTimeVal] = useState('');
  const [gpsLat, setGpsLat] = useState('');
  const [gpsLng, setGpsLng] = useState('');
  const [make, setMake] = useState('');
  const [model, setModel] = useState('');
  const [software, setSoftware] = useState('');
  const [presetId, setPresetId] = useState('');
  const [offset, setOffset] = useState(300);

  // Time shift state
  const [sign, setSign] = useState('+');
  const [shift, setShift] = useState({ years: 0, months: 0, days: 0, hours: 0, minutes: 0, seconds: 0 });

  const hasImages = list.length > 0;

  const resetImagesField = (field) => {
    list.forEach((im) => {
      const raw = im.edits && im.edits[field] ? im.edits[field].rawValue : undefined;
      store.setEdit(im.id, field, raw != null ? raw : '');
    });
  };

  const clearImagesField = (field) => {
    store.applyFieldValueToAll(field, null);
  };

  // ---- Date/Time group ----
  const applyDateTime = () => {
    if (!dateVal && !timeVal) return;
    store.applyFieldValueToAll('dateTimeOriginal', dtToExif(dateVal, timeVal));
  };

  // ---- GPS group ----
  const applyGps = () => {
    if (gpsLat === '' && gpsLng === '') return;
    const map = {};
    if (gpsLat !== '') map.gpsLat = Number(gpsLat);
    if (gpsLng !== '') map.gpsLng = Number(gpsLng);
    store.applyFieldGroupToAll(map);
  };
  const applyPresetAll = () => {
    const preset = (presets || []).find((p) => p.id === presetId);
    if (!preset) return;
    // Per-image random offset (each image gets its own offset sample)
    list.forEach((im) => {
      const newEdits = applyPresetToImage({ ...preset, offsetMeters: offset }, im.edits);
      store.setEdit(im.id, 'gpsLat', newEdits.gpsLat.value);
      store.setEdit(im.id, 'gpsLng', newEdits.gpsLng.value);
    });
  };

  // ---- Equip group ----
  const applyEquip = () => {
    if (make === '' && model === '') return;
    const map = {};
    if (make !== '') map.make = make;
    if (model !== '') map.model = model;
    store.applyFieldGroupToAll(map);
  };

  // ---- Software group ----
  const applySoftware = () => {
    if (software === '') return;
    store.applyFieldValueToAll('software', software);
  };

  // ---- Time shift ----
  const applyTimeShift = () => {
    const dir = sign === '-' ? -1 : 1;
    list.forEach((im) => {
      const cur = getDisplayValue(im, 'dateTimeOriginal', true) || (im.edits.dateTimeOriginal && im.edits.dateTimeOriginal.rawValue);
      const parsed = parseExifDate(cur);
      if (!parsed) return;
      const d = new Date(`${parsed.date}T${parsed.time}`);
      if (isNaN(d.getTime())) return;
      d.setFullYear(d.getFullYear() + dir * (shift.years || 0));
      d.setMonth(d.getMonth() + dir * (shift.months || 0));
      d.setDate(d.getDate() + dir * (shift.days || 0));
      d.setHours(d.getHours() + dir * (shift.hours || 0));
      d.setMinutes(d.getMinutes() + dir * (shift.minutes || 0));
      d.setSeconds(d.getSeconds() + dir * (shift.seconds || 0));
      const newDate = d.toISOString().slice(0, 10);
      const newTime = d.toTimeString().slice(0, 8);
      store.setEdit(im.id, 'dateTimeOriginal', dtToExif(newDate, newTime));
    });
  };

  const shiftField = (name, val) => setShift((s) => ({ ...s, [name]: Number(val) || 0 }));
  const shiftInputStyle = { width: '52px', padding: '4px', borderRadius: '4px', border: '1px solid #ccc', textAlign: 'center' };

  const GroupActions = ({ onApply, onClear, onReset, applyDisabled }) => (
    <div style={{ display: 'flex', gap: '6px', marginTop: '6px' }}>
      <button type="button" style={smallBtn} onClick={onApply} disabled={!hasImages || applyDisabled}>Apply to all</button>
      <button type="button" style={smallBtn} onClick={onClear} disabled={!hasImages}>✖ Clear all</button>
      <button type="button" style={smallBtn} onClick={onReset} disabled={!hasImages}>↺ Reset</button>
    </div>
  );

  return (
    <section style={sectionStyle}>
      <h3 style={{ margin: '0 0 10px', fontSize: '15px' }}>Batch Edit ({list.length} images)</h3>

      <div style={groupStyle}>
        <label style={labelStyle}>Date / Time</label>
        <div style={{ display: 'flex', gap: '6px' }}>
          <input type="date" value={dateVal} onChange={(e) => setDateVal(e.target.value)} style={inputStyle} placeholder="Date" />
          <input type="time" step="1" value={timeVal} onChange={(e) => setTimeVal(e.target.value)} style={inputStyle} placeholder="Time" />
        </div>
        <GroupActions onApply={applyDateTime} onClear={() => clearImagesField('dateTimeOriginal')} onReset={() => resetImagesField('dateTimeOriginal')} applyDisabled={!dateVal && !timeVal} />
      </div>

      <div style={groupStyle}>
        <label style={labelStyle}>GPS (Lat, Lng)</label>
        <div style={{ display: 'flex', gap: '6px' }}>
          <input type="number" step="any" value={gpsLat} onChange={(e) => setGpsLat(e.target.value)} style={inputStyle} placeholder="Latitude" />
          <input type="number" step="any" value={gpsLng} onChange={(e) => setGpsLng(e.target.value)} style={inputStyle} placeholder="Longitude" />
        </div>
        <GroupActions onApply={applyGps} onClear={() => store.applyFieldGroupToAll({ gpsLat: null, gpsLng: null })} onReset={() => { resetImagesField('gpsLat'); resetImagesField('gpsLng'); }} applyDisabled={gpsLat === '' && gpsLng === ''} />

        <label style={{ ...labelStyle, marginTop: '8px' }}>Preset (per-image random offset)</label>
        <div style={{ display: 'flex', gap: '6px', alignItems: 'center' }}>
          <select value={presetId} onChange={(e) => setPresetId(e.target.value)} style={inputStyle}>
            <option value="">— Select preset —</option>
            {(presets || []).map((p) => (
              <option key={p.id} value={p.id}>{getPresetDisplayName(p, t)}</option>
            ))}
          </select>
          <input type="range" min="0" max="5000" step="10" value={offset} onChange={(e) => setOffset(Number(e.target.value))} />
          <span style={{ fontSize: '12px', minWidth: '60px' }}>{offset} m</span>
          <button type="button" style={smallBtn} onClick={applyPresetAll} disabled={!hasImages || !presetId}>Apply</button>
        </div>
      </div>

      <div style={groupStyle}>
        <label style={labelStyle}>Make / Model</label>
        <div style={{ display: 'flex', gap: '6px' }}>
          <input type="text" value={make} onChange={(e) => setMake(e.target.value)} style={inputStyle} placeholder="Make" />
          <input type="text" value={model} onChange={(e) => setModel(e.target.value)} style={inputStyle} placeholder="Model" />
        </div>
        <GroupActions onApply={applyEquip} onClear={() => store.applyFieldGroupToAll({ make: null, model: null })} onReset={() => { resetImagesField('make'); resetImagesField('model'); }} applyDisabled={make === '' && model === ''} />
      </div>

      <div style={groupStyle}>
        <label style={labelStyle}>Software</label>
        <input type="text" value={software} onChange={(e) => setSoftware(e.target.value)} style={inputStyle} placeholder="Software" />
        <GroupActions onApply={applySoftware} onClear={() => clearImagesField('software')} onReset={() => resetImagesField('software')} applyDisabled={software === ''} />
      </div>

      <div style={groupStyle}>
        <label style={labelStyle}>Time Shift (apply delta to all)</label>
        <div style={{ display: 'flex', gap: '6px', alignItems: 'center', flexWrap: 'wrap' }}>
          <select value={sign} onChange={(e) => setSign(e.target.value)} style={{ ...shiftInputStyle, width: '44px' }}>
            <option value="+">+</option>
            <option value="-">−</option>
          </select>
          {['years', 'months', 'days', 'hours', 'minutes', 'seconds'].map((name) => (
            <label key={name} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', fontSize: '10px', color: '#888' }}>
              <input
                type="number"
                min="0"
                value={shift[name]}
                onChange={(e) => shiftField(name, e.target.value)}
                style={shiftInputStyle}
              />
              {name.replace(/s$/, '')}
            </label>
          ))}
          <button type="button" style={smallBtn} onClick={applyTimeShift} disabled={!hasImages}>Shift all</button>
        </div>
      </div>
    </section>
  );
}

export default BatchEditor;

// src/ui/vue/components/BatchEditor.vue
<template>
  <section class="batch-editor">
    <header class="batch-editor__header">
      <h2 class="batch-editor__title">{{ t('batch.title') }}</h2>
      <span class="batch-editor__count">{{ images.length }} {{ t('images.count') }}</span>
    </header>

    <p v-if="images.length === 0" class="batch-editor__empty">
      {{ t('batch.emptyHint') }}
    </p>

    <template v-else>
      <!-- DateTimeOriginal -->
      <div class="batch-editor__group">
        <label class="batch-editor__label">{{ t('edit.dateTimeOriginal') }}</label>
        <div class="batch-editor__row">
          <input
            type="date"
            class="batch-editor__input"
            v-model="batchValues.dateTimeOriginalDate"
          />
          <input
            type="time"
            step="1"
            class="batch-editor__input"
            v-model="batchValues.dateTimeOriginalTime"
          />
        </div>
        <div class="batch-editor__actions">
          <button
            type="button"
            class="batch-editor__btn batch-editor__btn--primary"
            :disabled="!hasBatchDateTime"
            @click="applyDateTime"
          >{{ t('batch.applyToAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="clearField('dateTimeOriginal')"
          >✖ {{ t('batch.clearAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="resetField('dateTimeOriginal')"
          >↺ {{ t('batch.reset') }}</button>
        </div>
      </div>

      <!-- GPS -->
      <div class="batch-editor__group">
        <label class="batch-editor__label">{{ t('edit.gps') }}</label>
        <div class="batch-editor__row">
          <input
            type="number"
            step="any"
            class="batch-editor__input"
            placeholder="Latitude"
            v-model="batchValues.gpsLat"
          />
          <input
            type="number"
            step="any"
            class="batch-editor__input"
            placeholder="Longitude"
            v-model="batchValues.gpsLng"
          />
        </div>
        <div class="batch-editor__actions">
          <button
            type="button"
            class="batch-editor__btn batch-editor__btn--primary"
            :disabled="!hasBatchGps"
            @click="applyGps"
          >{{ t('batch.applyToAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="clearField('gpsLat')"
          >✖ {{ t('batch.clearAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="resetField('gpsLat')"
          >↺ {{ t('batch.reset') }}</button>
        </div>
      </div>

      <!-- Make -->
      <div class="batch-editor__group">
        <label class="batch-editor__label">{{ t('edit.make') }}</label>
        <div class="batch-editor__row">
          <input
            type="text"
            class="batch-editor__input"
            v-model="batchValues.make"
          />
        </div>
        <div class="batch-editor__actions">
          <button
            type="button"
            class="batch-editor__btn batch-editor__btn--primary"
            :disabled="batchValues.make === ''"
            @click="applyField('make', batchValues.make)"
          >{{ t('batch.applyToAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="clearField('make')"
          >✖ {{ t('batch.clearAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="resetField('make')"
          >↺ {{ t('batch.reset') }}</button>
        </div>
      </div>

      <!-- Model -->
      <div class="batch-editor__group">
        <label class="batch-editor__label">{{ t('edit.model') }}</label>
        <div class="batch-editor__row">
          <input
            type="text"
            class="batch-editor__input"
            v-model="batchValues.model"
          />
        </div>
        <div class="batch-editor__actions">
          <button
            type="button"
            class="batch-editor__btn batch-editor__btn--primary"
            :disabled="batchValues.model === ''"
            @click="applyField('model', batchValues.model)"
          >{{ t('batch.applyToAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="clearField('model')"
          >✖ {{ t('batch.clearAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="resetField('model')"
          >↺ {{ t('batch.reset') }}</button>
        </div>
      </div>

      <!-- Software -->
      <div class="batch-editor__group">
        <label class="batch-editor__label">{{ t('edit.software') }}</label>
        <div class="batch-editor__row">
          <input
            type="text"
            class="batch-editor__input"
            v-model="batchValues.software"
          />
        </div>
        <div class="batch-editor__actions">
          <button
            type="button"
            class="batch-editor__btn batch-editor__btn--primary"
            :disabled="batchValues.software === ''"
            @click="applyField('software', batchValues.software)"
          >{{ t('batch.applyToAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="clearField('software')"
          >✖ {{ t('batch.clearAll') }}</button>
          <button
            type="button"
            class="batch-editor__btn"
            @click="resetField('software')"
          >↺ {{ t('batch.reset') }}</button>
        </div>
      </div>

      <!-- Time shift section -->
      <div class="batch-editor__group batch-editor__time-shift">
        <label class="batch-editor__label">{{ t('batch.timeShift') }}</label>
        <div class="batch-editor__row">
          <select v-model.number="timeShift.sign" class="batch-editor__select">
            <option :value="1">+</option>
            <option :value="-1">−</option>
          </select>
          <input type="number" min="0" placeholder="Y" v-model.number="timeShift.years" class="batch-editor__input" />
          <input type="number" min="0" placeholder="M" v-model.number="timeShift.months" class="batch-editor__input" />
          <input type="number" min="0" placeholder="D" v-model.number="timeShift.days" class="batch-editor__input" />
          <input type="number" min="0" placeholder="h" v-model.number="timeShift.hours" class="batch-editor__input" />
          <input type="number" min="0" placeholder="m" v-model.number="timeShift.minutes" class="batch-editor__input" />
          <input type="number" min="0" placeholder="s" v-model.number="timeShift.seconds" class="batch-editor__input" />
        </div>
        <div class="batch-editor__actions">
          <button
            type="button"
            class="batch-editor__btn batch-editor__btn--primary"
            :disabled="!hasTimeShift"
            @click="applyTimeShift"
          >{{ t('batch.applyTimeShift') }}</button>
        </div>
      </div>
    </template>
  </section>
</template>

<script setup>
import { computed, inject, reactive } from 'vue';
import { parseExifDate, dtToExif, t } from '../../../core/index.js';

const props = defineProps({
  images: { type: Array, default: () => [] },
});

const store = inject('imageStore');

// Local batch input values; empty string means "do not modify".
const batchValues = reactive({
  dateTimeOriginalDate: '',
  dateTimeOriginalTime: '',
  gpsLat: '',
  gpsLng: '',
  make: '',
  model: '',
  software: '',
});

const timeShift = reactive({
  sign: 1,
  years: 0, months: 0, days: 0,
  hours: 0, minutes: 0, seconds: 0,
});

const hasBatchDateTime = computed(() =>
  batchValues.dateTimeOriginalDate !== '' || batchValues.dateTimeOriginalTime !== ''
);
const hasBatchGps = computed(() =>
  batchValues.gpsLat !== '' || batchValues.gpsLng !== ''
);
const hasTimeShift = computed(() =>
  timeShift.years || timeShift.months || timeShift.days ||
  timeShift.hours || timeShift.minutes || timeShift.seconds
);

function applyDateTime() {
  if (!hasBatchDateTime.value) return;
  // Combine date+time into EXIF format; reuse first image's existing value as fallback.
  const first = props.images[0];
  const fallback = first && first.edits && first.edits.dateTimeOriginal;
  const fbRaw = (fallback && fallback.editedBy ? fallback.value : (first && first.summary && first.summary.dateTimeOriginal)) || '';
  const parsed = parseExifDate(fbRaw) || { date: '', time: '00:00:00' };
  const date = batchValues.dateTimeOriginalDate || parsed.date;
  const time = batchValues.dateTimeOriginalTime || parsed.time;
  const combined = dtToExif(date, time);
  store.applyFieldValueToAll('dateTimeOriginal', combined);
}

function applyGps() {
  if (!hasBatchGps.value) return;
  const map = {};
  if (batchValues.gpsLat !== '') map.gpsLat = Number(batchValues.gpsLat);
  if (batchValues.gpsLng !== '') map.gpsLng = Number(batchValues.gpsLng);
  store.applyFieldGroupToAll(map);
}

function applyField(field, value) {
  if (value === '') return;
  store.applyFieldValueToAll(field, value);
}

function clearField(field) {
  store.applyFieldValueToAll(field, null);
}

function resetField(field) {
  // Reset: clear user edits for this field on every image.
  for (const im of props.images) {
    const raw = im.summary && im.summary[field];
    if (raw !== undefined && raw !== null) {
      store.setEdit(im.id, field, raw);
    } else {
      store.setEdit(im.id, field, null);
    }
  }
}

function applyTimeShift() {
  if (!hasTimeShift.value) return;
  const sign = timeShift.sign;
  for (const im of props.images) {
    const edit = im.edits && im.edits.dateTimeOriginal;
    const baseVal = edit && edit.editedBy ? edit.value : (im.summary && im.summary.dateTimeOriginal);
    if (!baseVal) continue;
    const parsed = parseExifDate(baseVal);
    if (!parsed) continue;
    const shifted = shiftDateTime(parsed, timeShift, sign);
    if (shifted) {
      store.setEdit(im.id, 'dateTimeOriginal', shifted);
    }
  }
}

function shiftDateTime(parsed, ts, sign) {
  const d = new Date(`${parsed.date}T${parsed.time}`);
  if (isNaN(d.getTime())) return null;
  if (ts.years) d.setFullYear(d.getFullYear() + sign * ts.years);
  if (ts.months) d.setMonth(d.getMonth() + sign * ts.months);
  if (ts.days) d.setDate(d.getDate() + sign * ts.days);
  if (ts.hours) d.setHours(d.getHours() + sign * ts.hours);
  if (ts.minutes) d.setMinutes(d.getMinutes() + sign * ts.minutes);
  if (ts.seconds) d.setSeconds(d.getSeconds() + sign * ts.seconds);
  const pad = (n) => String(n).padStart(2, '0');
  const dateStr = `${d.getFullYear()}:${pad(d.getMonth() + 1)}:${pad(d.getDate())}`;
  const timeStr = `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
  return `${dateStr} ${timeStr}`;
}
</script>

<style scoped>
.batch-editor {
  background: var(--card-bg, #fff);
  border: 1px solid var(--border, #e4e6eb);
  border-radius: 10px;
  padding: 12px;
}
.batch-editor__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 10px;
}
.batch-editor__title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
}
.batch-editor__count {
  font-size: 12px;
  color: var(--app-fg, #888);
}
.batch-editor__empty {
  padding: 16px 8px;
  text-align: center;
  color: var(--app-fg, #888);
  font-size: 14px;
}
.batch-editor__group {
  margin-bottom: 12px;
  padding-bottom: 12px;
  border-bottom: 1px dashed var(--border, #e4e6eb);
}
.batch-editor__group:last-child {
  border-bottom: none;
  margin-bottom: 0;
  padding-bottom: 0;
}
.batch-editor__label {
  display: block;
  font-size: 12px;
  color: var(--app-fg, #666);
  margin-bottom: 4px;
}
.batch-editor__row {
  display: flex;
  align-items: center;
  gap: 6px;
  flex-wrap: wrap;
  margin-bottom: 6px;
}
.batch-editor__input {
  flex: 1 1 80px;
  min-height: 36px;
  padding: 0 8px;
  border: 1px solid var(--border, #d0d4dc);
  border-radius: 6px;
  background: var(--card-bg, #fff);
  color: inherit;
  font-size: 14px;
}
.batch-editor__select {
  min-height: 36px;
  padding: 0 8px;
  border: 1px solid var(--border, #d0d4dc);
  border-radius: 6px;
  background: var(--card-bg, #fff);
  color: inherit;
}
.batch-editor__actions {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
}
.batch-editor__btn {
  min-height: 32px;
  padding: 0 10px;
  border: 1px solid var(--border, #d0d4dc);
  border-radius: 6px;
  background: transparent;
  color: inherit;
  font-size: 13px;
  cursor: pointer;
}
.batch-editor__btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.batch-editor__btn--primary {
  background: #2f6feb;
  border-color: #2f6feb;
  color: #fff;
}
.batch-editor__btn--primary:disabled {
  background: var(--border, #ccc);
  border-color: var(--border, #ccc);
  color: var(--app-fg, #888);
}
.batch-editor__time-shift .batch-editor__input {
  flex: 1 1 50px;
  min-width: 50px;
}
</style>
