// src/ui/react/components/ExportPanel.jsx
import React from 'react';
import { useExporter } from '../hooks/useExporter.js';

const sectionStyle = { padding: '12px', borderBottom: '1px solid var(--border-color, #ddd)' };
const btnStyle = { padding: '8px 12px', minHeight: '36px', borderRadius: '4px', cursor: 'pointer' };

// Export buttons, progress bar, loading state.
export function ExportPanel({ images }) {
  const { isExporting, progress, exportOne, exportZip } = useExporter();
  const count = (images || []).length;
  const disabled = isExporting || count === 0;

  return (
    <section style={sectionStyle}>
      <h3 style={{ margin: '0 0 8px', fontSize: '15px' }}>Export</h3>
      <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
        <button type="button" style={btnStyle} disabled={disabled} onClick={() => exportOne(images)}>
          {isExporting ? 'Exporting…' : 'Download one by one'}
        </button>
        <button type="button" style={btnStyle} disabled={disabled} onClick={() => exportZip(images)}>
          {isExporting ? 'Exporting…' : 'Download ZIP'}
        </button>
        <span style={{ fontSize: '13px', color: '#666' }}>{count} image(s)</span>
      </div>

      {isExporting && (
        <div style={{ marginTop: '10px' }}>
          <div style={{ position: 'relative', height: '20px', background: '#eee', borderRadius: '4px', overflow: 'hidden' }}>
            <div
              style={{
                width: `${Math.max(0, Math.min(100, progress))}%`,
                height: '100%',
                background: '#1976d2',
                transition: 'width 120ms linear',
              }}
            />
            <span style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '12px', color: '#333' }}>
              {Math.round(progress)}%
            </span>
          </div>
        </div>
      )}
    </section>
  );
}

export default ExportPanel;

// src/ui/vue/components/ExportPanel.vue
<template>
  <section class="export-panel">
    <header class="export-panel__header">
      <h2 class="export-panel__title">{{ t('export.title') }}</h2>
      <span class="export-panel__count">{{ images.length }} {{ t('images.count') }}</span>
    </header>

    <div class="export-panel__actions">
      <button
        type="button"
        class="export-panel__btn export-panel__btn--primary"
        :disabled="images.length === 0 || isExporting"
        @click="emit('export-one')"
      >{{ t('export.oneByOne') }}</button>
      <button
        type="button"
        class="export-panel__btn export-panel__btn--primary"
        :disabled="images.length === 0 || isExporting"
        @click="emit('export-zip')"
      >{{ t('export.zip') }}</button>
    </div>

    <div v-if="isExporting" class="export-panel__progress">
      <div class="export-panel__progress-bar">
        <div
          class="export-panel__progress-fill"
          :style="{ width: progress + '%' }"
        ></div>
      </div>
      <div class="export-panel__progress-text">
        {{ Math.round(progress) }}%
        <span v-if="lastMessage">· {{ lastMessage }}</span>
      </div>
    </div>

    <p v-else-if="images.length === 0" class="export-panel__hint">
      {{ t('export.emptyHint') }}
    </p>
  </section>
</template>

<script setup>
import { inject } from 'vue';
import { t } from '../../../core/index.js';

defineProps({
  images: { type: Array, default: () => [] },
});

const emit = defineEmits(['export-one', 'export-zip']);

// App.vue wires the useExporter composable's state into these via inject so
// the panel can reflect progress without prop-drilling.
const isExporting = inject('isExporting', { value: false });
const progress = inject('progress', { value: 0 });
const lastMessage = inject('lastMessage', { value: '' });
</script>

<style scoped>
.export-panel {
  background: var(--card-bg, #fff);
  border: 1px solid var(--border, #e4e6eb);
  border-radius: 10px;
  padding: 12px;
}
.export-panel__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 10px;
}
.export-panel__title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
}
.export-panel__count {
  font-size: 12px;
  color: var(--app-fg, #888);
}
.export-panel__actions {
  display: flex;
  gap: 8px;
}
.export-panel__btn {
  flex: 1;
  min-height: 44px;
  padding: 0 14px;
  border: 1px solid var(--border, #d0d4dc);
  border-radius: 6px;
  background: transparent;
  color: inherit;
  cursor: pointer;
  font-size: 14px;
}
.export-panel__btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.export-panel__btn--primary {
  background: #2f6feb;
  border-color: #2f6feb;
  color: #fff;
}
.export-panel__btn--primary:disabled {
  background: var(--border, #ccc);
  border-color: var(--border, #ccc);
  color: var(--app-fg, #888);
}
.export-panel__progress {
  margin-top: 10px;
}
.export-panel__progress-bar {
  width: 100%;
  height: 8px;
  background: var(--border, #e4e6eb);
  border-radius: 4px;
  overflow: hidden;
}
.export-panel__progress-fill {
  height: 100%;
  background: #2f6feb;
  transition: width 0.15s ease;
}
.export-panel__progress-text {
  font-size: 12px;
  color: var(--app-fg, #666);
  margin-top: 4px;
}
.export-panel__hint {
  margin-top: 8px;
  font-size: 13px;
  color: var(--app-fg, #888);
  text-align: center;
}
</style>
