// src/ui/react/App.jsx
import React, { useState, useCallback, useMemo } from 'react';
import { SettingsBar } from './components/SettingsBar.jsx';
import { ImageList } from './components/ImageList.jsx';
import { ExifEditor } from './components/ExifEditor.jsx';
import { BatchEditor } from './components/BatchEditor.jsx';
import { PresetManager } from './components/PresetManager.jsx';
import { ExportPanel } from './components/ExportPanel.jsx';
import { useImageStore } from './hooks/useImageStore.js';
import { usePreset } from './hooks/usePreset.js';
import { changeLanguage, currentLanguage } from '../../core/index.js';
import { setTheme, getStoredTheme } from '../../platform/web/dom-i18n.js';

const shellStyle = {
  maxWidth: '720px',
  margin: '0 auto',
  fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  color: 'var(--text-color, #222)',
  background: 'var(--bg-color, #fff)',
};

// Root component. Accepts a readExif prop (decoder-bound) from the entry layer.
export function App({ readExif }) {
  const { store, images, selectedId, mode } = useImageStore(readExif);
  const preset = usePreset();
  const [language, setLanguage] = useState(() => currentLanguage());
  const [theme, setThemeState] = useState(() => getStoredTheme());

  const selectedImage = useMemo(
    () => images.find((im) => im.id === selectedId) || null,
    [images, selectedId]
  );

  const handleLanguageChange = useCallback(async (code) => {
    await changeLanguage(code);
    try { localStorage.setItem('exif-editor.language', code); } catch (_) { /* ignore */ }
    setLanguage(code);
  }, []);

  const handleThemeChange = useCallback((code) => {
    setTheme(code);
    setThemeState(code);
  }, []);

  const handleModeChange = useCallback((code) => {
    store.setMode(code);
  }, [store]);

  return (
    <div style={shellStyle}>
      <header style={{ padding: '12px', borderBottom: '1px solid var(--border-color, #ddd)' }}>
        <h1 style={{ margin: 0, fontSize: '18px' }}>ExifEditor</h1>
      </header>

      <SettingsBar
        language={language}
        onLanguageChange={handleLanguageChange}
        theme={theme}
        onThemeChange={handleThemeChange}
        mode={mode}
        onModeChange={handleModeChange}
      />

      <main>
        <ImageList
          images={images}
          selectedId={selectedId}
          onAddFiles={(fl) => store.addFiles(fl)}
          onSelect={(id) => store.selectImage(id)}
          onRemove={(id) => store.removeImage(id)}
          onClearAll={() => store.clearAll()}
        />

        {mode === 'single' ? (
          <ExifEditor
            image={selectedImage}
            store={store}
            presets={preset.presets}
            applyPresetToImage={preset.applyPresetToImage}
            getPresetDisplayName={preset.getPresetDisplayName}
            t={preset.t}
          />
        ) : (
          <BatchEditor
            images={images}
            store={store}
            presets={preset.presets}
            applyPresetToImage={preset.applyPresetToImage}
            getPresetDisplayName={preset.getPresetDisplayName}
            t={preset.t}
          />
        )}

        <PresetManager
          presets={preset.presets}
          refresh={preset.refresh}
          savePreset={preset.savePreset}
          deletePreset={preset.deletePreset}
          movePresetUp={preset.movePresetUp}
          movePresetDown={preset.movePresetDown}
          getPresetDisplayName={preset.getPresetDisplayName}
          t={preset.t}
        />

        <ExportPanel images={images} />
      </main>
    </div>
  );
}

export default App;

// src/ui/vue/App.vue
<template>
  <div class="app" :data-theme="theme">
    <SettingsBar
      :language="language"
      :theme="theme"
      :mode="store.mode"
      @change-language="onChangeLanguage"
      @change-theme="onChangeTheme"
      @change-mode="onChangeMode"
    />
    <main class="app__main">
      <ImageList
        :images="images"
        :selected-id="store.selectedId"
        @select="onSelectImage"
        @add-files="onAddFiles"
        @remove="onRemoveImage"
        @clear="onClearAll"
      />
      <ExifEditor
        v-if="store.selectedId && store.mode === 'single'"
        :image="selectedImage"
      />
      <BatchEditor
        v-else-if="store.mode === 'batch'"
        :images="images"
      />
      <PresetManager />
      <ExportPanel
        :images="images"
        @export-one="onExportOne"
        @export-zip="onExportZip"
      />
    </main>
  </div>
</template>

<script setup>
import { computed, onMounted, provide, ref } from 'vue';
import {
  changeLanguage,
  currentLanguage,
  onLanguageChanged,
  t,
} from '../../core/index.js';
import { getStoredTheme, setTheme } from '../../platform/web/dom-i18n.js';

import SettingsBar from './components/SettingsBar.vue';
import ImageList from './components/ImageList.vue';
import ExifEditor from './components/ExifEditor.vue';
import BatchEditor from './components/BatchEditor.vue';
import PresetManager from './components/PresetManager.vue';
import ExportPanel from './components/ExportPanel.vue';
import { useImageStore } from './composables/useImageStore.js';
import { useExporter } from './composables/useExporter.js';

const props = defineProps({
  readExif: { type: Function, required: true },
});

const { store, images } = useImageStore(props.readExif);
const { isExporting, progress, lastMessage, exportOne, exportZipAll } = useExporter();

const language = ref(currentLanguage());
const theme = ref(getStoredTheme());

// Reactively re-render t()-bound text when the core i18n language changes.
onLanguageChanged((lng) => {
  language.value = lng;
});

const selectedImage = computed(() =>
  images.value.find((im) => im.id === store.selectedId) || null
);

function onSelectImage(id) {
  store.selectImage(id);
}

async function onAddFiles(fileList) {
  await store.addFiles(fileList);
}

function onRemoveImage(id) {
  store.removeImage(id);
}

function onClearAll() {
  store.clearAll();
}

function onChangeMode(mode) {
  store.setMode(mode);
}

async function onChangeLanguage(code) {
  await changeLanguage(code);
  try { localStorage.setItem('exif-editor.language', code); } catch (_) { /* ignore */ }
  language.value = currentLanguage();
}

function onChangeTheme(code) {
  setTheme(code);
  theme.value = code;
}

function onExportOne() {
  exportOne(images.value);
}

function onExportZip() {
  exportZipAll(images.value);
}

// Expose shared values for child components via provide/inject pattern.
provide('t', t);
provide('language', language);
provide('imageStore', store);
provide('isExporting', isExporting);
provide('progress', progress);
provide('lastMessage', lastMessage);

onMounted(() => {
  // Re-sync language in case i18next resolved to a different value after init.
  language.value = currentLanguage();
});
</script>

<style scoped>
.app {
  min-height: 100vh;
  background: var(--app-bg, #f5f6f8);
  color: var(--app-fg, #1f2329);
  font-size: 16px;
  font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
}
.app__main {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 12px;
  max-width: 720px;
  margin: 0 auto;
}
:deep([data-theme='dark']) {
  --app-bg: #1a1d23;
  --app-fg: #e6e6e6;
  --card-bg: #2a2e36;
  --card-fg: #e6e6e6;
  --border: #3a3f4a;
}
</style>
